### ISSUE TITLE
Determine if Lookup Tool Already Exists

### ISSUE THREAD

**Issue by OSP123** [OSP123/myspace-lookup-tool#1]
User Story: As a Product Owner, I want to determine if the lookup tool concept already exists, in order to not waste my time solving a problem that doesn't need to be solved. 

Acceptance Criteria:

1. Do an analysis if tool already exists. 
2. If the tool does exist, what problems does it currently solve? What problems does it not solve for that are relevant? What does it do well? What could be done better? 
3. If the tool does not already, determine next step.

**Comment by OSP123** [comment]
Was not able to find an existing MySpace Lookup Tool. There were a lot of articles and resources on how to manually find an individual username and potentially find your old MySpace account. We can utilize the resources that others have gathered on finding an existing MySpace page to created an automated tool.

**Comment by Dcoxmen** [comment]
good to go
