### ISSUE TITLE
Determine Purpose and Scope of the Application

### ISSUE THREAD

**Issue by OSP123** [OSP123/myspace-lookup-tool#3]
User Story: As a product owner, I would like to know and write out the purpose and scope of the application, so that the team understands what the end goals are. 

Acceptance Crtieria:

1. Have a written set of purpose(s) for the application
2. Have a scope of time and features for the application written out

**Comment by OSP123** [comment]
Purpose: 
- Have a sample application built for students to utilize and reference as they're learning programming.
- We want to create an application that can allow users to submit some of their personal information (non-secure) and be able to find their old MySpace profile and possibly other older technology profiles. 

Scope: 

- Application shouldn't take longer than the length of the cohort
- Technologies covered should not exceed those covered in class or similar. 
- Others can submit pull requests to the application if they have followed procedures correctly and it contributes to the purposes of the application.
- Application should have multiple versions built, depending on technology breadth covered at time of cohort. For example, React version of application on client side shouldn't exist until React is covered.

**Comment by StaticCloud** [comment]
LGTM
